Delegation
theupdateframework/go-tuf pull request #117
Opened 2020-09-24 16:07 UTC by SimonMen65

The delegation branch fulfilled the function of delegation. Detailed instructions are added in readme file.
This branch is developed based on fuchsia branch, which can be dated closer to now. This is my first time using pull request, so not sure if I'm sending a right request. I think you can choose to merge it to fuchsia or master or even create a new branch.

2020-09-25 02:26 UTC, trishankatdatadog commented on verify/verify.go
> +	if role == "root" || role == "targets" || role == "snapshot" || role == "timestamp" {
use switch-case statement 🙂

2020-09-25 10:50 UTC, shibumi requested changes

2020-09-25 10:50 UTC, shibumi commented on local_store.go
> +			if nameJSON != "root.json" && nameJSON != "targets.json" && nameJSON != "snapshot.json" && nameJSON != "timestamp.json" && strings.HasSuffix(nameJSON, ".json") {
These are a lot statements. I wonder if it would be possible to make this easier to read. Maybe more than one if statement?.. What do you think? :)

2020-09-25 10:50 UTC, shibumi commented on repo_test.go
> +	//_, err = r.GenKey("foo")
Are these comments supposed to stay there? if yes, why?

2020-09-25 23:33 UTC, closed without merging

2020-09-28 10:19 UTC, lukpueh commented
Was this PR closed because of #115 being merged? Should we re-open and change the PR destination to master?

2020-09-28 10:30 UTC, shibumi commented
@lukpueh I think so, this PR definitely needs a rebase on current master in this case.

2020-09-28 10:31 UTC, lukpueh commented
> @lukpueh I think so, this PR definitely needs a rebase on current master in this case.

@SimonMen65, can you do that?

2020-09-28 10:43 UTC, lukpueh commented
@SimonMen65, please also consider re-reading the [dev guidelines](https://github.com/secure-systems-lab/lab-guidelines/blob/master/dev-workflow.md) I shared with you a while ago. In particular, I'd like to remind you about the notes on [commits and commit messages](https://github.com/secure-systems-lab/lab-guidelines/blob/master/commits.md). Thanks!

2020-10-06 23:10 UTC, JustinCappos commented
@SimonMen65 How is this coming along?  We'd love to accept your changes, but we need this in a format we can accept that keeps our code maintainable.

2020-10-06 23:13 UTC, SimonMen65 commented
Dear Prof.Cappos,
It’s been quite busy after class started, many of my classes replaced exams
by individual projects, with much more workload than a usual exam.

I’ll try to finish all these changes by this week.

Best,
Simon

Justin Cappos <notifications@github.com>于2020年10月6日 周二19:10写道：

> @SimonMen65
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SimonMen65&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OMYr4iI_zH0SDpFJI75QIQ&m=SfLF_ovBeDg7vYu0Rp9IfBuCOZlgo3-5HhtpyEFLbV0&s=9Mq3kp7y7qKdYPB4Ro3Y_iFRoPENGKC-6057G92qdMY&e=>
> How is this coming along? We'd love to accept your changes, but we need
> this in a format we can accept that keeps our code maintainable.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_theupdateframework_go-2Dtuf_pull_117-23issuecomment-2D704600349&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OMYr4iI_zH0SDpFJI75QIQ&m=SfLF_ovBeDg7vYu0Rp9IfBuCOZlgo3-5HhtpyEFLbV0&s=KjAoq7uA6t-37VQA9CGpGMv00Za61BB86NPMCTntpRI&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOPTCL5SY3R5FTYXQ7VWV4DSJOPXLANCNFSM4RYPVLKA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OMYr4iI_zH0SDpFJI75QIQ&m=SfLF_ovBeDg7vYu0Rp9IfBuCOZlgo3-5HhtpyEFLbV0&s=Rq40ExY9C3XNEhurJ7hLi1Sa_sgwHb8PfmNsk329vDs&e=>
> .
>

2020-10-08 19:37 UTC, SimonMen65 commented
Updated the code with respect to these comments, should I raise another PR or what's the next step?

Sorry for asking but this is my first time using the PR things.

If another PR, which branch should I merge it to?

2020-10-08 19:56 UTC, shibumi commented
@SimonMen65 can you re-open the PR by yourself or does @trishankatdatadog need to do this?

2020-10-08 20:03 UTC, shibumi commented
ahh okay.. now I know what is going on. @trishankatdatadog Github auto-closed this PR when you merged the Fuchsia PR. because this PR has the fuchisa PR as target.

@SimonMen65  you need to-open your PR against the master branch. Also rebase against master.

2020-10-08 20:10 UTC, trishankatdatadog commented
> ahh okay.. now I know what is going on. @trishankatdatadog Github auto-closed this PR when you merged the Fuchsia PR. because this PR has the fuchisa PR as target.

That explains a lot. I was like, "I don't even remember doing that..."

2020-10-08 21:52 UTC, SimonMen65 commented
@shibumi What do you mean by rebase?

2020-10-09 07:24 UTC, shibumi commented
@SimonMen65 https://git-scm.com/docs/git-rebase

1. git remote add upstream https://github.com/theupdateframework/go-tuf.git
2. git checkout master && git pull upstream master
3. git checkout delegation
4. git rebase master
5. git push origin delegation
6. Open a new PR via Github Web UI

2020-10-09 08:10 UTC, lukpueh commented
> @SimonMen65 you need to-open your PR against the master branch. Also rebase against master.

FYI, you don't need to open a new PR, you can just open this one and [change its destination (aka. base)](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request) to master.

2020-10-09 08:16 UTC, lukpueh commented
> @shibumi What do you mean by rebase?

You find details about using `git rebase` to keep you fork in sync in our [git history guidelines](https://github.com/secure-systems-lab/lab-guidelines/blob/master/git-history.md), which are part of our [development guidelines](https://github.com/secure-systems-lab/lab-guidelines/blob/master/dev-workflow.md). Let me know if you have any questions about those guidelines.

2020-10-15 17:19 UTC, SimonMen65 commented
I don't think I'm able to re-open this PR. I just finished rebasing and will open a new PR

2020-10-15 17:24 UTC, SimonMen65 commented
@lukpueh One question about rebase, now it shows up that I'm working on a branch called (no branch, rebasing delegation) which appears as (1353a38), I think this is like a temporary branch that only created for PR. If I would make further changes to the delegation branch, I need to checkout delegation, and I might need to rebase every time I want to send PR. Am i right?

2020-10-15 19:38 UTC, shibumi commented
@SimonMen65 it might be easier to just clone the current master and trying to cherry-pick your changes on the new master branch

2020-10-16 08:05 UTC, lukpueh commented
>  now it shows up that I'm working on a branch called (no branch, rebasing delegation)

That sounds like you were in the middle of a rebase. Probably it stopped because there were conflicts? What did `git status` show? At any rate you should finish the rebase before you continue development on your `delegation` branch.

>  I might need to rebase every time I want to send PR. Am i right?

Not necessarily, only if the remote branch (e.g. `master`) you want to PR against has diverged from your local version of that branch. Did you read the "keep your fork in sync" docs I pointed you to?  Feel free to ping me on slack if you need further help.

2020-10-18 19:23 UTC, SimonMen65 commented
@lukpueh Thanks a lot for ur instructions, there are conflicts during rebase and already solved them. I have started a new PR because I can't reopen this, probably because it's not me who closed this PR. Please visit the ew PR.