[Delegations prereq 7] Make signers addressible by key ID in LocalStore
theupdateframework/go-tuf pull request #197
Opened 2021-12-10 23:06 UTC by ethan-lowman-dd

Splitting up https://github.com/theupdateframework/go-tuf/pull/175

2021-12-13 18:28 UTC, mnm678 approved these changes

2021-12-16 17:05 UTC, ethan-lowman-dd commented
Realized I'm missing new tests here. Will add.

2022-01-28 21:42 UTC, asraa requested changes
@ethan-lowman-dd did you want to add tests?

2022-01-28 23:00 UTC, ethan-lowman-dd commented
> @ethan-lowman-dd did you want to add tests?

@asraa The functionality of `SignersForKeyIDs` is tested to some extent in existing tests (since this PR just adds a step of indirection for key lookup) but I will add some dedicated tests too.

2022-02-09 22:05 UTC, asraa approved these changes

2022-03-01 00:06 UTC, ethan-lowman-dd commented
@asraa Added tests for the changed functionality.

2022-03-01 15:43 UTC, mnm678 approved these changes

2022-03-07 18:44 UTC, ethan-lowman-dd commented
Rebasing dismissed reviews. There shouldn't have been any material changes in the rebase.

2022-03-07 21:06 UTC, mnm678 approved these changes

2022-03-08 22:15 UTC, asraa approved these changes

2022-03-08 22:49 UTC, merged