docs: add security.md
theupdateframework/go-tuf pull request #412
Opened 2022-10-07 17:43 UTC by asraa

Signed-off-by: Asra Ali <asraa@google.com>

Please fill in the fields below to submit a pull request.  The more information that is provided, the better.

Fixes [#<Issue>](https://github.com/theupdateframework/go-tuf/issues/371)
Release Notes: 

**Types of changes**:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

**Description of the changes being introduced by the pull request**:

**Please verify and check that the pull request fulfills the following requirements**:

- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

2022-10-07 17:55 UTC, trishankatdatadog submitted a review, later dismissed

2022-10-07 17:57 UTC, trishankatdatadog commented
LGTM, Asra, including the Google Form. Thanks so much for doing this!

2022-10-11 21:12 UTC, asraa commented on docs/SECURITY.md
> +
Clarified!

2022-10-11 23:35 UTC, rdimitrov approved these changes

2022-10-12 17:43 UTC, znewman01 submitted a review, later dismissed

2022-10-12 19:34 UTC, trishankatdatadog requested changes

2022-10-12 19:34 UTC, trishankatdatadog commented on docs/SECURITY.md
> +Please do **not** create a public GitHub issue to submit vulnerability reports. The GitHub issue tracker is intended for bug reports and feature requests. Major feature requests, such as design chang
```suggestion
Please do **not** create a public GitHub issue or pull request to submit vulnerability reports. These public trackers are intended for non-time-sensitive bug reports and feature requests. Major feature requests, such as design changes to the specification, should be proposed via a [TUF Augmentation Protocol](https://theupdateframework.github.io/specification/latest/#tuf-augmentation-proposal-tap-support) (TAP).
```

2022-10-12 20:45 UTC, trishankatdatadog submitted a review, later dismissed

2022-10-13 11:53 UTC, rdimitrov reviewed
Let's resolve the DCO failure and I think we should be okay 👍

2022-10-13 13:56 UTC, asraa commented
SG! I really don't know what happened with that DCO failure. Maybe trishank had pushed some commit with co-author?

2022-10-13 14:02 UTC, asraa reviewed
Fixed DCO, just squashed the commit onto master

2022-10-13 15:07 UTC, trishankatdatadog approved these changes

2022-10-13 15:38 UTC, merged